<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('news')->insert([
            'content' => "<p> Jabung, 12 Agustus 2024 - Kesenian Malam Bulan Purnama yang diadakan oleh Pemerintah Desa Jabung pada 21 Juni 2024 sukses menggelar malam penuh seni dan budaya. Acara yang mengusung tema 'Budaya adalah seni yang diangkat menjadi seperangkat keyakinan' ini menampilkan pertunjukan tunggal dari grup Reog Simo Mulang Joyo, yang berhasil memukau penonton dengan aksi panggung mereka.</p><p>Reog Simo Mulang Joyo, yang telah dikenal sebagai salah satu grup kesenian kebanggaan SMP N 4 Ponorogo, menampilkan pertunjukan yang sarat dengan energi dan keindahan seni tradisional. Dalam balutan kostum yang megah dan iringan musik tradisional yang dinamis, para penari berhasil membawa penonton masuk ke dalam alur cerita yang ditampilkan, menciptakan suasana magis di bawah sinar purnama.</p><p>Penampilan grup Reog ini tidak hanya menjadi hiburan, tetapi juga merupakan bentuk pelestarian budaya yang sarat dengan nilai-nilai sejarah dan kepercayaan yang telah diwariskan dari generasi ke generasi. Antusiasme penonton terlihat dari sorakan dan tepuk tangan meriah yang mengiringi setiap gerakan penari.</p><p>Acara ini juga menjadi ajang bagi masyarakat Desa Jabung untuk berkumpul dan merayakan kebersamaan, sekaligus memperkuat ikatan komunitas melalui warisan budaya yang mereka junjung tinggi. Selain pertunjukan Reog, pengunjung juga menikmati berbagai sajian kuliner tradisional yang tersedia di sekitar alun-alun, menambah kehangatan malam itu.</p><p>Kesenian Malam Bulan Purnama tahun ini, dengan penampilan spesial dari Reog Simo Mulang Joyo, menjadi salah satu momen bersejarah yang tak terlupakan bagi masyarakat Desa Jabung dan pengunjung yang hadir. Semoga acara seperti ini terus dilestarikan, menjadi wadah untuk merayakan dan menjaga kekayaan budaya yang kita miliki.</p>",
            'title' => "Kesenian Malam Bulan Purnama Desa Jabung: Reog Simo Mulang Joyo Memukau Penonton",
            'writer' => "Cindy Alya P.",
            'created_at' => '2024-08-12 07:22:00',
            'photo_path' => "dummyImage1.jpg"
        ]);
        DB::table('news')->insert([
            'content' => "<p> Jabung, 12 Agustus 2024 - Desa Jabung kembali memancarkan semangat gotong royong melalui acara tahunan Bersih Desa yang selalu dinantikan warga. Tahun ini, kegiatan diawali dengan Khotmil Qur'an di seluruh masjid desa, menciptakan suasana penuh keberkahan dan kebersamaan.</p><p>Puncak keceriaan dirasakan saat seluruh warga mengikuti Jalan Sehat pada Kamis, 23 Mei 2024. Tidak hanya sekadar berjalan kaki, namun kali ini acara terasa lebih istimewa dengan hadirnya Bupati Ponorogo, Sugiri Sancoko, yang turut serta berjalan bersama warga. 'Saya suka suasana seperti ini, berbaur dengan masyarakat tanpa ada sekat,' ujar Bupati Sugiri Sancoko dengan senyum hangat. Kehadirannya semakin mempererat ikatan antara pemerintah dan masyarakat Desa Jabung.</p><p>Kemeriahan Bersih Desa Jabung mencapai puncaknya dengan Pagelaran Seni Malam Bulan Purnama. Penampilan memukau dari Kesenian Gajah Dwi Panggo Budoyo Jabung II berhasil menyihir penonton, membawa mereka larut dalam keindahan budaya lokal. Alunan musik tradisional dan gerakan tari yang indah menjadi penutup yang sempurna, meninggalkan kesan mendalam bagi semua yang hadir.</p><p>Bersih Desa Jabung 2024 bukan hanya sekadar acara tahunan, tetapi juga wujud nyata dari kekompakan dan kebanggaan warga dalam menjaga dan merayakan tradisi.</p>",
            'title' => "Bersih Desa Jabung 2024: Dihadiri Bupati Ponorogo dan Dimeriahkan Pagelaran Seni",
            'writer' => "Cindy Alya P.",
            'created_at' => '2024-08-12 07:30:00',
            'photo_path' => "dummyImage2.jpg"
        ]);
        DB::table('news')->insert([
            'content' => "<p> Jabung, 12 Agustus 2024 - Desa Jabung kembali menunjukkan semangat inovasi dengan menggelar 'Lomba Cipta Menu PMT Balita Non-Tepung dan Non-Beras' pada 11 Agustus 2024. Acara yang berlangsung meriah ini bertujuan untuk menggali kreativitas warga dalam menciptakan menu bergizi bagi balita, dengan mengutamakan penggunaan bahan-bahan lokal selain tepung dan beras.</p><p>Dalam lomba ini, para peserta dari berbagai dusun di Desa Jabung berlomba-lomba menampilkan kreasi menu PMT (Pemberian Makanan Tambahan) yang tidak hanya sehat, tetapi juga menarik dan enak di lidah balita. Berbagai inovasi bahan makanan seperti umbi-umbian, kacang-kacangan, dan sayuran segar menjadi bintang utama dalam setiap hidangan yang disajikan.</p><p>Semangat dan antusiasme warga terlihat jelas dalam persiapan dan pelaksanaan lomba ini. Selain berfungsi sebagai sarana edukasi, kegiatan ini juga memperkuat ikatan sosial antarwarga yang bekerja sama dalam menciptakan menu-menu terbaik. Hal ini mencerminkan kekompakan dan rasa peduli yang tinggi terhadap kesehatan generasi penerus.</p><p>Setelah melalui penilaian ketat oleh juri yang terdiri dari ahli gizi dan tokoh masyarakat, pemenang lomba pun diumumkan. Hasilnya, menu yang memadukan potensi lokal dengan kandungan gizi seimbang berhasil meraih predikat terbaik. Kreasi yang dihasilkan tidak hanya memberikan inspirasi bagi para orang tua di Desa Jabung, tetapi juga menjadi contoh untuk diterapkan di berbagai tempat lainnya.</p><p>Acara ini diharapkan dapat menjadi momentum untuk terus mendorong peningkatan kualitas kesehatan balita di Desa Jabung, serta menjadi inspirasi bagi desa-desa lain dalam mengembangkan program serupa. Dengan adanya kegiatan seperti ini, diharapkan para orang tua semakin sadar akan pentingnya gizi seimbang dan terus berinovasi dalam menciptakan menu makanan yang sehat dan menarik untuk balita mereka.</p>",
            'title' => "Kreativitas Warga Jabung: Lomba Cipta Menu PMT Balita Non-Tepung dan Non-Beras",
            'writer' => "Cindy Alya P.",
            'created_at' => '2024-08-12 07:40:00',
            'photo_path' => "dummyImage3.jpg"
        ]);
        DB::table('news')->insert([
            'content' => "<p> Jabung, 12 Agustus 2024 - Desa Jabung menyambut HUT RI Ke-79 dengan penuh antusiasme dan semangat kebangsaan yang tinggi. Desa Jabung menggelar Apel Pembukaan sebagai tanda dimulainya rangkaian perayaan kemerdekaan yang penuh makna. Apel Pembukaan ini berlangsung di lapangan utama desa.</p><p>Usai Apel Pembukaan, rangkaian acara HUT RI Ke-79 di Desa Jabung akan memasuki fase yang sangat dinantikan oleh seluruh warga. Hari berikutnya, desa akan menjadi tuan rumah untuk Turnamen Tenis Meja yang diikuti oleh para pemain lokal dengan berbagai tingkat keterampilan. Turnamen ini tidak hanya sebagai ajang kompetisi tetapi juga sebagai kesempatan bagi masyarakat untuk berinteraksi dan mendukung atlet favorit mereka.</p><p>Selanjutnya, kompetisi Bola Voli Antar RW Putra-Putri akan menambah semarak perayaan. Pertandingan ini menghadirkan semangat persaingan yang sehat dan mempromosikan olahraga sebagai sarana kebersamaan di antara berbagai RW di desa. Pertandingan bola voli ini diharapkan menjadi tontonan yang menghibur dan mempererat hubungan antarwarga.</p><p>Untuk memeriahkan acara, akan digelar juga Lomba Anak-Anak yang diikuti oleh peserta dari berbagai usia. Lomba ini bertujuan untuk menggali kreativitas dan bakat anak-anak serta memberikan mereka kesempatan untuk menunjukkan keterampilan mereka di hadapan keluarga dan teman-teman. Selain itu, Lomba Cipta Menu PMT akan menampilkan keahlian memasak para peserta dengan menu-menu kreatif dan lezat yang menjadi kebanggaan desa.</p><p>Tidak ketinggalan, Pawai Kesenian Desa Jabung akan menjadi salah satu highlight dari rangkaian acara. Pawai ini menampilkan pertunjukan seni tradisional yang menggambarkan kekayaan budaya Desa Jabung, menjadikannya acara yang penuh warna dan keunikan.</p><p>Sebagai penutup dari perayaan yang meriah ini, Desa Jabung akan menggelar Pesta Memancing. Acara ini menawarkan kesempatan bagi warga untuk bersantai sambil menikmati keindahan alam desa dan merasakan keseruan memancing. Pesta Memancing ini diharapkan dapat menjadi ajang rekreasi yang menyenangkan bagi seluruh keluarga.</p><p>Desa Jabung mengundang seluruh warga dan masyarakat sekitar untuk bergabung dalam perayaan HUT RI Ke-79 ini. Mari bersama-sama merayakan kemerdekaan dengan penuh semangat, kebanggaan, dan kebersamaan. Jangan lewatkan kesempatan untuk terlibat dalam setiap acara yang telah dipersiapkan dengan penuh cinta dan dedikasi.</p>",
            'title' => "Meriahkan HUT RI Ke-79: Desa Jabung Gelar Apel Pembukaan",
            'writer' => "Cindy Alya P.",
            'created_at' => '2024-08-12 07:50:00',
            'photo_path' => "dummyImage4.jpg"
        ]);
        DB::table('news')->insert([
            'content' => "<p> Jabung, 12 Agustus 2024 - Turnamen Bola Voli Antar RW yang berlangsung di Desa Jabung sejak 5 Agustus 2024 telah mencapai puncaknya dengan semangat kompetisi yang semakin memanas. Acara tahunan yang digelar untuk memeriahkan HUT RI ke-79 ini sukses menarik perhatian warga desa, terutama karena partisipasi aktif dari semua RW yang berlaga dengan penuh antusiasme.</p><p>Turnamen yang berlangsung selama sembilan hari ini tidak hanya menjadi ajang adu ketangkasan, tetapi juga mempererat tali silaturahmi antarwarga. Setiap pertandingan selalu diwarnai dengan sorak-sorai pendukung masing-masing tim yang memenuhi lapangan desa. Para pemain menunjukkan kemampuan terbaik mereka, dengan strategi permainan yang semakin matang di setiap babak.</p><p>Kini, dengan final yang semakin dekat, persaingan antar tim RW semakin sengit. Semua tim bertekad untuk membawa pulang gelar juara dan mengharumkan nama RW mereka. Pertandingan final yang akan digelar pada 13 Agustus 2024 diharapkan akan menjadi puncak dari turnamen yang telah dinantikan oleh seluruh warga Desa Jabung.</p><p>Tak hanya sekadar pertandingan, turnamen ini juga menjadi momentum bagi warga desa untuk bersatu dan berbagi semangat kebersamaan dalam rangka merayakan kemerdekaan Indonesia. Kemenangan bukanlah segalanya, karena di balik kompetisi ini, ada rasa persaudaraan yang semakin kuat di antara warga Desa Jabung.</p><p>Tetap semangat kepada semua tim yang akan bertanding di final, dan semoga kemenangan sejati diraih dengan sportifitas yang tinggi!</p>",
            'title' => "Turnamen Bola Voli Antar RW di Desa Jabung: Perebutan Gelar Juara Memanas Menjelang Final!",
            'writer' => "Cindy Alya P.",
            'created_at' => '2024-08-12 08:00:00',
            'photo_path' => "dummyImage5.jpg"
        ]);
        DB::table('news')->insert([
            'content' => "<p>Jabung, 12 Agustus 2024 - Desa Jabung kembali menegaskan komitmennya dalam upaya pencegahan stunting melalui kegiatan Rembuk Stunting yang diselenggarakan pada 25 Juni 2024 lalu. Acara ini menjadi salah satu langkah dalam proses penyusunan Rencana Kerja Pemerintah Desa (RKP Desa) untuk tahun 2025, yang bertujuan meningkatkan kualitas hidup warga dan mewujudkan Desa Jabung yang lebih sehat dan sejahtera.</p><p>Kegiatan yang berlangsung di Balai Desa Jabung tersebut dihadiri oleh berbagai elemen masyarakat. Mereka berkumpul bersama untuk merumuskan strategi pencegahan stunting yang efektif dan berkelanjutan, sejalan dengan prioritas pembangunan desa yang telah disepakati bersama.</p><p>Selama diskusi yang berlangsung secara intensif, berbagai isu terkait stunting di Desa Jabung dibahas dengan mendalam. Para peserta rembuk sepakat bahwa salah satu fokus utama yang perlu diperhatikan adalah peningkatan kualitas gizi bagi ibu hamil dan balita, yang merupakan kelompok paling rentan terhadap stunting. Selain itu, peningkatan akses terhadap layanan kesehatan yang berkualitas, edukasi gizi bagi keluarga, serta pengembangan program Posyandu yang lebih optimal juga menjadi rekomendasi utama dalam rembuk tersebut.</p><p>Kegiatan ini juga menjadi ajang bagi masyarakat untuk menyampaikan aspirasi dan masukan terkait permasalahan yang mereka hadapi di lapangan. Hal ini sangat penting untuk memastikan bahwa program yang dirumuskan benar-benar sesuai dengan kebutuhan dan kondisi riil masyarakat.</p><p>Hasil dari Rembuk Stunting ini akan menjadi acuan dalam penyusunan RKP Desa tahun 2025. Rencana ini akan disahkan dalam Musyawarah Desa yang akan datang, di mana seluruh elemen masyarakat diharapkan dapat memberikan dukungan penuh untuk keberhasilan program-program yang telah direncanakan. Dengan adanya sinergi antara pemerintah desa dan masyarakat, diharapkan Desa Jabung dapat mengatasi masalah stunting secara efektif dan menjadi desa yang lebih maju dan sejahtera.</p><p>Melalui rembuk stunting ini, Desa Jabung tidak hanya berfokus pada pencegahan stunting, tetapi juga menanamkan kesadaran akan pentingnya kesehatan dan kesejahteraan anak-anak sebagai investasi masa depan desa. Dengan semangat kebersamaan, Desa Jabung siap melangkah ke depan dengan optimisme, menghadapi tantangan dan mencapai visi pembangunan yang lebih baik.</p>",
            'title' => "Rembuk Stunting Desa Jabung 2024: Dalam rangka Penyusunan RKP Desa 2025",
            'writer' => "Cindy Alya P.",
            'created_at' => '2024-08-12 08:10:00',
            'photo_path' => "dummyImage6.jpg"
        ]);
    }
}
